### ISSUE TITLE
云函数 setCookbook 似乎有问题

### ISSUE THREAD

**Issue by nexmoe** [LeeJim/HowToCookOnMiniprogram#6]
res is undefined

**Comment by LeeJim** [comment]
应该要创建对应的 collection 先

**Comment by LeeJim** [comment]
应该要创建对应的 collection 先

**Comment by nexmoe** [comment]
创建了，但仍然有问题

**Comment by nexmoe** [comment]
函数日志返回结果如下

```
{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"ReferenceError: res is not defined\n    at Runtime.exports.main [as handler] (/var/user/index.js:65:3)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","statusCode":430}
```

**Comment by LeeJim** [comment]
确实有问题，我修复下
